/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * v1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 *
 * Example: openapi-generator-cli generate -i openapi.yaml -g cpp-single -o src/cpp/client-single
 *
 * DO NOT edit these files manually.
 */

/*
 * ApiResponse.h
 *
 * Describes the result of uploading an image resource
 */

#ifndef SINGLE_CPP_CLIENT_ApiResponse_H_
#define SINGLE_CPP_CLIENT_ApiResponse_H_


#include <string>
#include "json.hpp"
#include "Helpers.h"

namespace SingleCppClient {


class ApiResponse {
public:

    /* Constructors */
    ApiResponse();
    ApiResponse(std::string jsonString);

    /* Destructor */
    virtual ~ApiResponse();

    /* Retrieve a JSON representation of this class */
    nlohmann::json toJson();

    /* Fills in members of this class from the JSON object representing it */
    void fromJson(std::string jsonObj);

    /* Get  */
    int getCode();
    /* Get  */
    std::string getType();
    /* Get  */
    std::string getMessage();

    /* Set  */
    void setCode(int  code);
    /* Set  */
    void setType(std::string  type);
    /* Set  */
    void setMessage(std::string  message);

private:
    int code{};
    std::string type{};
    std::string message{};
};
}

#endif /* SINGLE_CPP_CLIENT_ApiResponse_H_ */
