/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * v1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 *
 * Example: openapi-generator-cli generate -i openapi.yaml -g cpp-single -o src/cpp/client-single
 *
 * DO NOT edit these files manually.
 */

/*
 * Order.h
 *
 * An order for a pets from the pet store
 */

#ifndef SINGLE_CPP_CLIENT_Order_H_
#define SINGLE_CPP_CLIENT_Order_H_


#include <string>
#include "json.hpp"
#include "Helpers.h"

namespace SingleCppClient {


class Order {
public:

    /* Constructors */
    Order();
    Order(std::string jsonString);

    /* Destructor */
    virtual ~Order();

    /* Retrieve a JSON representation of this class */
    nlohmann::json toJson();

    /* Fills in members of this class from the JSON object representing it */
    void fromJson(std::string jsonObj);

    /* Get  */
    long getId();
    /* Get  */
    long getPetId();
    /* Get  */
    int getQuantity();
    /* Get  */
    std::string getShipDate();
    /* Get Order Status */
    std::string getStatus();
    /* Get  */
    bool isComplete();

    /* Set  */
    void setId(long  id);
    /* Set  */
    void setPetId(long  petId);
    /* Set  */
    void setQuantity(int  quantity);
    /* Set  */
    void setShipDate(std::string  shipDate);
    /* Set Order Status */
    void setStatus(std::string  status);
    /* Set  */
    void setComplete(bool  complete);

private:
    long id{};
    long petId{};
    int quantity{};
    std::string shipDate{};
    std::string status{};
    bool complete{};
};
}

#endif /* SINGLE_CPP_CLIENT_Order_H_ */
