/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * v1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 *
 * Example: openapi-generator-cli generate -i openapi.yaml -g cpp-single -o src/cpp/client-single
 *
 * DO NOT edit these files manually.
 */


#include "Tag.h"

using namespace SingleCppClient;

Tag::Tag()
{
    id = long(0);
    name = std::string();
}

Tag::Tag(std::string jsonString)
{
    this->fromJson(jsonString);
}

Tag::~Tag()
{
}

void Tag::fromJson(std::string jsonObj)
{
    nlohmann::json object = nlohmann::json::parse(jsonObj);
    const char *idKey = "id";

    if (object.contains(idKey))
    {
        nlohmann::json value = object[idKey];
        jsonToValue(&id, value, "long");

    }

    const char *nameKey = "name";

    if (object.contains(nameKey))
    {
        nlohmann::json value = object[nameKey];
        jsonToValue(&name, value, "std::string");

    }

}

nlohmann::json Tag::toJson()
{
    nlohmann::json object = nlohmann::json::object();
    object["id"] = getId();
    object["name"] = getName();
    return object;
}

 long Tag::getId()
{
    return id;
}

void Tag::setId(long  id)
{
    this->id = id;
}

 std::string Tag::getName()
{
    return name;
}

void Tag::setName(std::string  name)
{
    this->name = name;
}

