/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * v1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 *
 * Example: openapi-generator-cli generate -i openapi.yaml -g cpp-single -o src/cpp/client-single
 *
 * DO NOT edit these files manually.
 */

/*
 * Tag.h
 *
 * A tag for a pet
 */

#ifndef SINGLE_CPP_CLIENT_Tag_H_
#define SINGLE_CPP_CLIENT_Tag_H_


#include <string>
#include "json.hpp"
#include "Helpers.h"

namespace SingleCppClient {


class Tag {
public:

    /* Constructors */
    Tag();
    Tag(std::string jsonString);

    /* Destructor */
    virtual ~Tag();

    /* Retrieve a JSON representation of this class */
    nlohmann::json toJson();

    /* Fills in members of this class from the JSON object representing it */
    void fromJson(std::string jsonObj);

    /* Get  */
    long getId();
    /* Get  */
    std::string getName();

    /* Set  */
    void setId(long  id);
    /* Set  */
    void setName(std::string  name);

private:
    long id{};
    std::string name{};
};
}

#endif /* SINGLE_CPP_CLIENT_Tag_H_ */
