/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * v1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 *
 * Example: openapi-generator-cli generate -i openapi.yaml -g cpp-single -o src/cpp/client-single
 *
 * DO NOT edit these files manually.
 */

/*
 * User.h
 *
 * A User who is purchasing from the pet store
 */

#ifndef SINGLE_CPP_CLIENT_User_H_
#define SINGLE_CPP_CLIENT_User_H_


#include <string>
#include "json.hpp"
#include "Helpers.h"

namespace SingleCppClient {


class User {
public:

    /* Constructors */
    User();
    User(std::string jsonString);

    /* Destructor */
    virtual ~User();

    /* Retrieve a JSON representation of this class */
    nlohmann::json toJson();

    /* Fills in members of this class from the JSON object representing it */
    void fromJson(std::string jsonObj);

    /* Get  */
    long getId();
    /* Get  */
    std::string getUsername();
    /* Get  */
    std::string getFirstName();
    /* Get  */
    std::string getLastName();
    /* Get  */
    std::string getEmail();
    /* Get  */
    std::string getPassword();
    /* Get  */
    std::string getPhone();
    /* Get User Status */
    int getUserStatus();

    /* Set  */
    void setId(long  id);
    /* Set  */
    void setUsername(std::string  username);
    /* Set  */
    void setFirstName(std::string  firstName);
    /* Set  */
    void setLastName(std::string  lastName);
    /* Set  */
    void setEmail(std::string  email);
    /* Set  */
    void setPassword(std::string  password);
    /* Set  */
    void setPhone(std::string  phone);
    /* Set User Status */
    void setUserStatus(int  userStatus);

private:
    long id{};
    std::string username{};
    std::string firstName{};
    std::string lastName{};
    std::string email{};
    std::string password{};
    std::string phone{};
    int userStatus{};
};
}

#endif /* SINGLE_CPP_CLIENT_User_H_ */
